feat: compare license additions from head vs base (#9)
This adds logic that lists the added packages/licenses from the HEAD pull request compared to the base branch. The differences are then submitted as pull request comment.

This is done by generating an SBOM + fetching licenses & exporting the list as TSV (using our `grant-summarize` command). The differences are checked using [`comm`].

[`comm`]: https://www.man7.org/linux/man-pages/man1/comm.1.html

diff --git a/.github/workflows/run-license-check.yaml b/.github/workflows/run-license-check.yaml
--- a/.github/workflows/run-license-check.yaml
+++ b/.github/workflows/run-license-check.yaml
@@ -47,7 +47,28 @@ permissions:
   contents: read
 
 jobs:
+  # Note: the workflow should never fail if license violations are found on the base.
+  #       This is important as a pull_request (HEAD) may change the license rules
+  #       in a way that would make the base branch no longer compliant
+  #       (e.g., if the company puts new policies).
+  check-licenses-base-ref:
+    name: Check Licenses (base branch)
+    permissions:
+      contents: read
+      pull-requests: write
+    uses: ./.github/workflows/run-generate-sbom-and-check-licenses.yaml
+    with:
+      # Checkout the base branch of the pull request.
+      checkout_ref: ${{ github.event.pull_request.base.ref }}
+      rules: ${{ inputs.rules }}
+      ecosystems: ${{ inputs.ecosystems }}
+      output_formats: tsv
+      output_summary_artifact_name: Grant Summary (base branch)
+      output_sbom_artifact_name: SBOM (base branch)
+      is_same_repository: ${{ inputs.is_same_repository }}
+
   check-licenses-head-ref:
+    name: Check Licenses (HEAD)
     permissions:
       contents: read
       pull-requests: write
@@ -71,14 +92,14 @@ jobs:
 
     needs:
       - check-licenses-head-ref
+      - check-licenses-base-ref
 
     permissions:
       contents: read
       pull-requests: write
 
     env:
-      # The summary.html file is generated by grant-license-checker/action.yaml
-      HTML_FILE_PATH: ./results_head/summary.html
+      HTML_FILE_PATH: ./results/summary.html
       PR_NUMBER: ${{ github.event.pull_request.number }}
       # There could be multiple comments with the author 'github-action[bot]',
       # thus we need to look for an identifier that demonstrates we are
@@ -89,8 +110,73 @@ jobs:
       - name: Download Analysis Results
         uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
         with:
+          name: Grant Summary (base branch)
+          path: ./results_base
+
+      - name: Download Analysis Results
+        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
+        with:
           name: Grant Summary (HEAD)
           path: ./results_head
+
+      # Compares HEAD and base (using the 'comm' command), and stores them
+      # as HTML inside HTML_FILE_PATH.
+      - name: Compare Differences
+        shell: bash
+        env:
+          file1: ./results_base/summary.tsv
+          file2: ./results_head/summary.tsv
+        run: |
+          out_dir=$(dirname "$HTML_FILE_PATH")
+          mkdir "$out_dir"
+
+          # Options used:
+          #   1) '-1' => do not print TSV rows that are only present in base
+          #              (i.e., do not show deleted/removed packages)
+          #   2) '-3' => do not print lines that are present both in base and head
+          #              (i.e., do not show unchanged)
+          # This results to 'comm' only showing packages that were added.
+          diffs=$(
+            comm -13 <(sort "$file1") <(sort "$file2") \
+              `# Sanitize potential HTML inside package & license names` \
+              | sed 's/</\&lt;/g;s/>/\&gt;/g' \
+              `# Drop control characters from the comm command` \
+              `# otherwise it leads to formatting issues` \
+              | col -b
+          )
+
+          addition_count=$(echo "$diffs" | wc -l)
+
+          {
+            echo "## Differences Found"
+
+            # Use 'awk' to check if the diffs are empty instead of 'wc -l'
+            # because the 'col' command always return '\n' even if the contents
+            # are empty (thus 'wc -l' is always >= 1).
+            if awk 'NF {exit 1}' <(printf "%s" "$diffs"); then
+              echo ":white_check_mark: No packages or licenses were added."
+            else
+              echo ":warning: **$addition_count packages or licenses were added.**"
+              echo ""
+              echo "<details><summary>Expand</summary>"
+              echo "<pre>"
+              echo -e "License\tPackage" # TSV header
+              echo "$diffs" # TSV rows
+              echo "</pre>"
+              echo "</details>"
+              echo ""
+            fi
+          } > "$HTML_FILE_PATH"
+
+      - name: Generate Results
+        shell: bash
+        run: |
+          {
+            echo "## Summary"
+            echo "<details><summary>Expand</summary>"
+            cat ./results_head/summary.html
+            echo "</details>"
+          } >> "$HTML_FILE_PATH"
 
       - name: Validate HTML Report
         shell: bash
@@ -156,3 +242,13 @@ jobs:
               "$endpoint" \
               -F "body=@$HTML_FILE_PATH" \
               "${cmd_args[@]}"
+
+      # Fails if HEAD license compliance didn't pass.
+      - name: Check Conclusion
+        if: ${{ needs.check-licenses-head-ref.outputs.check_conclusion != 'pass' }}
+        env:
+          RULES: ${{ inputs.rules }}
+        run: |
+          echo "HEAD license check failed. Make sure the pull request is compliant with:" >&2
+          printf "%s\n" "$RULES" >&2
+          exit 1
